In [1]:
import numpy as np
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
%matplotlib inline

In [2]:
sns.set(style='white', context='notebook', rc={'figure.figsize':(14,10)})

In [3]:
data = pd.read_csv('data\\analysis_dataset.csv', sep=";")
data = data.dropna()

In [4]:
data.describe()

,Unnamed: 0,coin,maxdiam,mindiam,weight,enddate,startdate,axis,material_ ae,material_ ar,material_ av,material_ cu,material_ el,material_ pb,denom_cat,mint_cat,collection_cat
count,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.0,5947.0,5947.000000,5947.000000,5947.000000
mean,20555.791155,13190.413318,22.638572,22.056408,9.066516,19.536573,-11.971078,7.085758,0.824617,0.163612,0.005381,0.001682,0.0,0.0,7.819573,47.617454,18676.555911
std,11889.223994,12367.686653,7.238582,7.151399,7.545908,233.549261,251.033218,3.869731,0.380326,0.369954,0.073163,0.040975,0.0,0.0,14.739066,36.252888,10770.810910
min,11.000000,41.000000,0.700000,0.700000,0.120000,-493.000000,-530.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,-1.000000,-1.000000,-1.000000
25%,10157.000000,4157.000000,17.000000,16.850000,3.520000,-200.000000,-300.000000,5.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.0,-1.000000,11.000000,9505.500000
50%,20727.000000,6821.000000,22.000000,22.000000,6.790000,161.000000,138.000000,7.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.0,2.000000,40.000000,18730.000000
75%,30799.000000,18259.500000,28.500000,28.000000,13.960000,212.000000,198.000000,12.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.0,5.000000,84.000000,27937.500000
max,41078.000000,41964.000000,48.000000,47.000000,64.320000,400.000000,300.000000,12.000000,1.000000,1.000000,1.000000,1.000000,0.0,0.0,51.000000,115.000000,37217.000000

In [5]:
# make material great again
mat_cols = [x for x in data.columns.tolist() if "material" in x]
data["material"] = 0
i = 1
for c in mat_cols:
    data["material"] = np.where(data[c]==1, i, data["material"])
    i +=1
    del data[c]

In [6]:
data.describe()

,Unnamed: 0,coin,maxdiam,mindiam,weight,enddate,startdate,axis,denom_cat,mint_cat,collection_cat,material
count,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000,5947.000000
mean,20555.791155,13190.413318,22.638572,22.056408,9.066516,19.536573,-11.971078,7.085758,7.819573,47.617454,18676.555911,1.174710
std,11889.223994,12367.686653,7.238582,7.151399,7.545908,233.549261,251.033218,3.869731,14.739066,36.252888,10770.810910,0.417712
min,11.000000,41.000000,0.700000,0.700000,0.120000,-493.000000,-530.000000,1.000000,-1.000000,-1.000000,-1.000000,0.000000
25%,10157.000000,4157.000000,17.000000,16.850000,3.520000,-200.000000,-300.000000,5.000000,-1.000000,11.000000,9505.500000,1.000000
50%,20727.000000,6821.000000,22.000000,22.000000,6.790000,161.000000,138.000000,7.000000,2.000000,40.000000,18730.000000,1.000000
75%,30799.000000,18259.500000,28.500000,28.000000,13.960000,212.000000,198.000000,12.000000,5.000000,84.000000,27937.500000,1.000000
max,41078.000000,41964.000000,48.000000,47.000000,64.320000,400.000000,300.000000,12.000000,51.000000,115.000000,37217.000000,4.000000

In [ ]:
sns.pairplot(data, hue='material')

C:\Users\fredi\Anaconda3\envs\ftp\lib\site-packages\seaborn\distributions.py:283: UserWarning: Data must have variance to compute a kernel density estimate.
  warnings.warn(msg, UserWarning)
C:\Users\fredi\Anaconda3\envs\ftp\lib\site-packages\seaborn\distributions.py:283: UserWarning: Data must have variance to compute a kernel density estimate.
  warnings.warn(msg, UserWarning)

In [13]:
import umap.umap_ as umap
reducer = umap.UMAP()
scaled_data = StandardScaler().fit_transform(data)
embedding = reducer.fit_transform(scaled_data)
embedding.shape

ModuleNotFoundError: No module named 'umap.umap_'; 'umap' is not a package